### ISSUE TITLE
DeviceMapper - problem

### ISSUE THREAD

**Issue by michalkolar** [parodyne/esos#171]
Hi,

I have a problem with Esos storage when blockio create, connect it to the customer on the KVM server, he can install the operating system. 

After rebooting Esos storage you see in the partition of disk (using fdisk -l). If you delete a device in Esos toi, already'm not going to add, in a survey it, it offers only devicep1 devicep2, but not the entire disk - without pX.

Thanks,
Kolar Michal

**Comment by msmith626** [comment]
Wow, oddly enough, another use just email'd me directly about this same
issue yesterday. The issue would have existed for many years, so its funny
I have 2 users with the same problem within a day of each other. Anyhow...
this happens because Linux (ESOS) reads the device's disk label and can do
so since you're using vdisk_blockio (could happen with pass-through handler
as well). In the TUI we hide devices from selection that can't be opened
with O_EXCL and since that device has other DM's (for partitions) created
from it, it doesn't show it.

I'll fix this in ESOS... what version/branch are you using?

A work-around is to either add the new entry with scstadmin at the command
line or use the TUI and select a different device (eg, the partition) sync
the config, then manually edit /etc/scst.conf to use the right device then
run 'scstadmin -config /etc/scst.conf' to apply changes.


--Marc

**Comment by michalkolar** [comment]
Hi,

i using latest version (because 10gbit firmware brocade br1020 - friend Feldsam created issue about a few days back).

It would be best to blockio only show physical LVM volume and do not show the sub partition of lvm volume.
eg.
lvm_hdd0
lvm_hdd1
lvm_hdd2

without

lvm_hdd0p1
lvm_hdd0p2





Thanks!

Michal Kolar

**Comment by msmith626** [comment]
I removed the partition-probing of LVM logical volumes from the rc.lvm2 script, so this shouldn't happen now with LV's, although, as I mentioned in the comments above, it could be an issue for some device types, although that seems rare.

Closing this now, and if we have issues again in the future, we'll revisit it.

--Marc

**Comment by michalkolar** [comment]
Thank you for resolving this problem 👍 🥇
