### ISSUE TITLE
TUI not expanding text window during initiator selection/showing duplicate names

### ISSUE THREAD

**Issue by stuarthopkins** [parodyne/esos#172]
When using ESOS for iSCSI exports I found some poor behaviour of TUI in that selecting the correct initiator is not possible due to the UI panel not expanding to fit the initiator names (see attached screenshot). It also appears that the same initiator is being listed multiple times (due to multipath connections) when they should only be listed once (as its the initiator name that is used, not their IP address).

Can we get the UI fixed please so that we can see the full initiator name, and have the list filtered so that the IP is dropped from each initiator and we only see each initiator once.

<img width="460" alt="esos-iscsi names" src="https://cloud.githubusercontent.com/assets/1296952/13914121/5c0e0f70-ef44-11e5-9e0c-a853c1ce79a7.png">

**Comment by msmith626** [comment]
Hi,

I decided to handle this differently... instead of trying to expand the dialogs/screens, I created the prettyShrinkStr() function to reduce a string to a maximum size, and if it exceeds the maximum, it shrinks it nicely (eg, "iqn.1998-01.com.vmware:simon-e-blah-blah:s78sd" might show up as "iqn.1998-01.co...h-blah:s78sd"). For most strings this should work nicely as there can be some unique part at the end or beginning to distinguish one from another.

I updated the select-initiators dialog to use this and a couple others that may tend to be long (so far the targets and sessions widgets on main screen).

As I see others that are problematic, I'll update them to use the new function.

I'll have this changed committed later today.

--Marc
