### ISSUE TITLE
SNMP Configuration

### ISSUE THREAD

**Issue by Domskis** [parodyne/esos#204]
Hi,
I am brand new to this so please let me know if I am posting this in the wrong spot. 
I am running Esos and would like to monitor if any HDD fail. Tried setting up SNMP without any success. Running snmpd start just hangs there for a bit, finishes but service does not start, does not listen on any interfaces, snmpwalk locahost returns timeout. Could anyone help me with this ?

**Comment by msmith626** [comment]
Hi,

On a ESOS 1.3.2 I performed the following just now, here is a
transcript of the commands and output:

--snip--
[root@tgthost1 ~]# /etc/rc.d/rc.snmpd start
Starting snmpd...
[root@tgthost1 ~]# ps ax | grep snmpd
15865 root       0:00 /usr/sbin/snmpd -LS0-6d -Lf /dev/null -p
/var/run/snmpd.pid
15868 root       0:00 grep snmpd
[root@tgthost1 ~]# netstat -natup | grep snmpd
udp        0      0 127.0.0.1:161           0.0.0.0:*
         15865/snmpd
udp        0      0 0.0.0.0:54159           0.0.0.0:*
         15865/snmpd
[root@tgthost1 ~]# snmpwalk -mALL -v1 -cpublic localhost system
RFC1213-MIB::sysDescr.0 = STRING: "Linux tgthost1.parodyne.com
4.9.65-esos.prod #1 SMP Fri Dec 1 06:34:14 UTC 2017 x86_64"
RFC1213-MIB::sysObjectID.0 = OID: NET-SNMP-TC::linux
DISMAN-EVENT-MIB::sysUpTimeInstance = Timeticks: (5901) 0:00:59.01
RFC1213-MIB::sysContact.0 = STRING: "Me <me@example.org>"
RFC1213-MIB::sysName.0 = STRING: "tgthost1.parodyne.com"
RFC1213-MIB::sysLocation.0 = STRING: "Sitting on the Dock of the Bay"
RFC1213-MIB::sysServices.0 = INTEGER: 72
SNMPv2-MIB::sysORLastChange.0 = Timeticks: (0) 0:00:00.00
SNMPv2-MIB::sysORID.1 = OID: SNMP-MPD-MIB::snmpMPDCompliance
SNMPv2-MIB::sysORID.2 = OID: SNMP-USER-BASED-SM-MIB::usmMIBCompliance
SNMPv2-MIB::sysORID.3 = OID: SNMP-FRAMEWORK-MIB::snmpFrameworkMIBCompliance
SNMPv2-MIB::sysORID.4 = OID: SNMPv2-MIB::snmpMIB
SNMPv2-MIB::sysORID.5 = OID: SNMP-VIEW-BASED-ACM-MIB::vacmBasicGroup
SNMPv2-MIB::sysORID.6 = OID: TCP-MIB::tcpMIB
SNMPv2-MIB::sysORID.7 = OID: RFC1213-MIB::ip
SNMPv2-MIB::sysORID.8 = OID: UDP-MIB::udpMIB
SNMPv2-MIB::sysORID.9 = OID: SNMP-NOTIFICATION-MIB::snmpNotifyFullCompliance
SNMPv2-MIB::sysORID.10 = OID: NOTIFICATION-LOG-MIB::notificationLogMIB
SNMPv2-MIB::sysORDescr.1 = STRING: The MIB for Message Processing and
Dispatching.
SNMPv2-MIB::sysORDescr.2 = STRING: The management information
definitions for the SNMP User-based Security Model.
SNMPv2-MIB::sysORDescr.3 = STRING: The SNMP Management Architecture MIB.
SNMPv2-MIB::sysORDescr.4 = STRING: The MIB module for SNMPv2 entities
SNMPv2-MIB::sysORDescr.5 = STRING: View-based Access Control Model for SNMP.
SNMPv2-MIB::sysORDescr.6 = STRING: The MIB module for managing TCP
implementations
SNMPv2-MIB::sysORDescr.7 = STRING: The MIB module for managing IP and
ICMP implementations
SNMPv2-MIB::sysORDescr.8 = STRING: The MIB module for managing UDP
implementations
SNMPv2-MIB::sysORDescr.9 = STRING: The MIB modules for managing SNMP
Notification, plus filtering.
SNMPv2-MIB::sysORDescr.10 = STRING: The MIB module for logging SNMP
Notifications.
SNMPv2-MIB::sysORUpTime.1 = Timeticks: (0) 0:00:00.00
SNMPv2-MIB::sysORUpTime.2 = Timeticks: (0) 0:00:00.00
SNMPv2-MIB::sysORUpTime.3 = Timeticks: (0) 0:00:00.00
SNMPv2-MIB::sysORUpTime.4 = Timeticks: (0) 0:00:00.00
SNMPv2-MIB::sysORUpTime.5 = Timeticks: (0) 0:00:00.00
SNMPv2-MIB::sysORUpTime.6 = Timeticks: (0) 0:00:00.00
SNMPv2-MIB::sysORUpTime.7 = Timeticks: (0) 0:00:00.00
SNMPv2-MIB::sysORUpTime.8 = Timeticks: (0) 0:00:00.00
SNMPv2-MIB::sysORUpTime.9 = Timeticks: (0) 0:00:00.00
SNMPv2-MIB::sysORUpTime.10 = Timeticks: (0) 0:00:00.00
[root@tgthost1 ~]#
--snip--

What version of ESOS are you running? What happens when you perform
the same steps above on your system?

(To make snmpd start at boot, be sure to edit /etc/rc.conf to your liking.)


--Marc

**Comment by Domskis** [comment]
Hi Marc,

Thank you so much for this answer. I do not think I was doing it right. Everything works same as yours.
I have an LSI card in the system and ESOS can see it. All the tools Storcli and such are installed and working, I need to monitor the hard drives to see if any are dead.
Would you be able to point me how to set up the conning so snap would work on all interface ?

Regards

Sent with [ProtonMail](https://protonmail.com) Secure Email.

> -------- Original Message --------
> Subject: Re: [parodyne/esos] SNMP Configuration (#204)
> Local Time: December 6, 2017 3:11 PM
> UTC Time: December 6, 2017 8:11 PM
> From: notifications@github.com
> To: parodyne/esos <esos@noreply.github.com>
> Domskis <domskis@protonmail.com>, Author <author@noreply.github.com>
>
> Hi,
>
> On a ESOS 1.3.2 I performed the following just now, here is a
> transcript of the commands and output:
>
> --snip--
> [root@tgthost1 ~]# /etc/rc.d/rc.snmpd start
> Starting snmpd...
> [root@tgthost1 ~]# ps ax | grep snmpd
> 15865 root 0:00 /usr/sbin/snmpd -LS0-6d -Lf /dev/null -p
> /var/run/snmpd.pid
> 15868 root 0:00 grep snmpd
> [root@tgthost1 ~]# netstat -natup | grep snmpd
> udp 0 0 127.0.0.1:161 0.0.0.0:*
> 15865/snmpd
> udp 0 0 0.0.0.0:54159 0.0.0.0:*
> 15865/snmpd
> [root@tgthost1 ~]# snmpwalk -mALL -v1 -cpublic localhost system
> RFC1213-MIB::sysDescr.0 = STRING: "Linux tgthost1.parodyne.com
> 4.9.65-esos.prod #1 SMP Fri Dec 1 06:34:14 UTC 2017 x86_64"
> RFC1213-MIB::sysObjectID.0 = OID: NET-SNMP-TC::linux
> DISMAN-EVENT-MIB::sysUpTimeInstance = Timeticks: (5901) 0:00:59.01
> RFC1213-MIB::sysContact.0 = STRING: "Me <me@example.org>"
> RFC1213-MIB::sysName.0 = STRING: "tgthost1.parodyne.com"
> RFC1213-MIB::sysLocation.0 = STRING: "Sitting on the Dock of the Bay"
> RFC1213-MIB::sysServices.0 = INTEGER: 72
> SNMPv2-MIB::sysORLastChange.0 = Timeticks: (0) 0:00:00.00
> SNMPv2-MIB::sysORID.1 = OID: SNMP-MPD-MIB::snmpMPDCompliance
> SNMPv2-MIB::sysORID.2 = OID: SNMP-USER-BASED-SM-MIB::usmMIBCompliance
> SNMPv2-MIB::sysORID.3 = OID: SNMP-FRAMEWORK-MIB::snmpFrameworkMIBCompliance
> SNMPv2-MIB::sysORID.4 = OID: SNMPv2-MIB::snmpMIB
> SNMPv2-MIB::sysORID.5 = OID: SNMP-VIEW-BASED-ACM-MIB::vacmBasicGroup
> SNMPv2-MIB::sysORID.6 = OID: TCP-MIB::tcpMIB
> SNMPv2-MIB::sysORID.7 = OID: RFC1213-MIB::ip
> SNMPv2-MIB::sysORID.8 = OID: UDP-MIB::udpMIB
> SNMPv2-MIB::sysORID.9 = OID: SNMP-NOTIFICATION-MIB::snmpNotifyFullCompliance
> SNMPv2-MIB::sysORID.10 = OID: NOTIFICATION-LOG-MIB::notificationLogMIB
> SNMPv2-MIB::sysORDescr.1 = STRING: The MIB for Message Processing and
> Dispatching.
> SNMPv2-MIB::sysORDescr.2 = STRING: The management information
> definitions for the SNMP User-based Security Model.
> SNMPv2-MIB::sysORDescr.3 = STRING: The SNMP Management Architecture MIB.
> SNMPv2-MIB::sysORDescr.4 = STRING: The MIB module for SNMPv2 entities
> SNMPv2-MIB::sysORDescr.5 = STRING: View-based Access Control Model for SNMP.
> SNMPv2-MIB::sysORDescr.6 = STRING: The MIB module for managing TCP
> implementations
> SNMPv2-MIB::sysORDescr.7 = STRING: The MIB module for managing IP and
> ICMP implementations
> SNMPv2-MIB::sysORDescr.8 = STRING: The MIB module for managing UDP
> implementations
> SNMPv2-MIB::sysORDescr.9 = STRING: The MIB modules for managing SNMP
> Notification, plus filtering.
> SNMPv2-MIB::sysORDescr.10 = STRING: The MIB module for logging SNMP
> Notifications.
> SNMPv2-MIB::sysORUpTime.1 = Timeticks: (0) 0:00:00.00
> SNMPv2-MIB::sysORUpTime.2 = Timeticks: (0) 0:00:00.00
> SNMPv2-MIB::sysORUpTime.3 = Timeticks: (0) 0:00:00.00
> SNMPv2-MIB::sysORUpTime.4 = Timeticks: (0) 0:00:00.00
> SNMPv2-MIB::sysORUpTime.5 = Timeticks: (0) 0:00:00.00
> SNMPv2-MIB::sysORUpTime.6 = Timeticks: (0) 0:00:00.00
> SNMPv2-MIB::sysORUpTime.7 = Timeticks: (0) 0:00:00.00
> SNMPv2-MIB::sysORUpTime.8 = Timeticks: (0) 0:00:00.00
> SNMPv2-MIB::sysORUpTime.9 = Timeticks: (0) 0:00:00.00
> SNMPv2-MIB::sysORUpTime.10 = Timeticks: (0) 0:00:00.00
> [root@tgthost1 ~]#
> --snip--
>
> What version of ESOS are you running? What happens when you perform
> the same steps above on your system?
>
> (To make snmpd start at boot, be sure to edit /etc/rc.conf to your liking.)
>
> --Marc
>

**Comment by msmith626** [comment]
By default ESOS uses email to send alerts... the "health_chk.sh" script
runs in a cron and checks PD and LD states which will send an email
notification if there are failures.

Not sure I understand your last sentence about "setup the conning so snap
would work on all interface"?

--Marc

**Comment by Domskis** [comment]
Hi Marc,

I got the SNMP to work. Thank you so much for your help !

Regards

Dominik
